### ISSUE TITLE
Redirect loop in Edge

### ISSUE THREAD

**Issue by dicksnel** [marmelab/ra-auth-msal#12] opened 2023-11-29 14:52 UTC
In version 1.2.0 a redirect loop is introduced.

It seems to only happens in Edge. After redirecting back to /auth-login, the application initiates another redirect to fetch a token, causing a loop. This does not happen in Firefox.

Reverting to 1.1.0 fixes the issues.

![image](https://github.com/marmelab/ra-auth-msal/assets/21058511/57308cca-d8b9-4e4b-ade0-8ed60c13c30b)

**Comment by jonathan-marmelab** [comment] 2023-12-06 08:21
Hello @dicksnel,

I am the developper that implemented the deep link feature. I wasn't able to reproduce the bug on Edge (Linux), can you give me more information about your setup ?

It seems that there is an error on the Microsoft token enpoint on your logs, can you give me more information about this error as well ?

Have a nice day,
Jonathan

**Comment by dicksnel** [comment] 2023-12-08 14:30
@jonathan-marmelab I changed my implementation from:

`const myMSALObj = new PublicClientApplication(msalConfig);`

To:

```
const myMSALObj = new PublicClientApplication(msalConfig);
myMSALObj.initialize().then(() => {}});
```

Which seems to have fixed the issue. The demo project mentions:

[https://github.com/marmelab/ra-auth-msal/blob/main/packages/demo-react-admin/src/App.tsx

`const myMSALObj = new PublicClientApplication(msalConfig);`](https://github.com/marmelab/ra-auth-msal/blob/706d7f477309e50d117391b16989c3a834e49d3f/packages/demo-react-admin/src/App.tsx#L36C7-L36C7)

But this is deprecated. Newer versions of MSAL require async initialization.

Thank for the help!

**Comment by dicksnel** [comment] 2023-12-11 13:31
I made a mistake and was still running the old version. The issues is not fixed. But setting [enableDeepLinkRedirect](https://github.com/marmelab/ra-auth-msal/blob/main/packages/ra-auth-msal/Readme.md#enabledeeplinkredirect) to false does work as a temporary fix.

**Comment by slax57** [comment] 2023-12-12 13:38
Thanks for the additional information.

I'll reopen the issue then.

Can you please specify what version of `@azure/msal-browser` shows the issue, and what version does not?

Thanks.

**Comment by djhi** [comment] 2024-05-06 10:14
I can't reproduce this error using our demo with MS Entra. I'm using Edge on Linux though.

**Comment by fzaninotto** [comment] 2024-06-18 13:12
I'm closing this issue because we got no news for some time. Feel free to add a "how to reproduce" comment if you want us to take a look at it.

**Closed by fzaninotto** 2024-06-18 13:12 UTC
Labels: need more info
